name = "glubs"
version = "0.2.0"

description = "WebVTT and SRT parser and serializer."

licences = ["Apache-2.0"]

repository = { type = "github", user = "philipgiuliani", repo = "glubs" }

internal_modules = [
  "glubs/timestamp"
]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
simplifile = "~> 1.0"
