name = "glubs"
version = "0.1.0"

description = "WebVTT parser and payload tokenizer"
licences = ["Apache-2.0"]
repository = { type = "github", user = "philipgiuliani", repo = "glubs" }
links = [{ title = "Website", href = "https://github.com/philipgiuliani/glubs" }]

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
simplifile = "~> 1.0"
